domain: "wordpress-lab"
servername: "wordpress-lab.com"

debian_deps: [ 'python-openssl' , 'curl' ]
debian_php_deps: [ 'php-curl', 'php-fpm' , 'php-mysql' , 'php-curl' , 'php-gd' , 'php-intl' , 'php-mbstring' , 'php-soap' , 'php-xml' , 'php-xmlrpc' , 'php-zip' ]
debian_mysql_deps: [ 'mysql-server' , 'python-mysqldb', ' python3-mysqldb' ]


centos_deps: [ 'pyOpenSSL' , 'curl', 'python2-cryptography', 'epel-release' ,'yum-utils', 'python36-pyOpenSSL', 'python36-crypto' ]   
centos_php_deps : [ 'php-cli', 'php-fpm', 'php-mysql', 'php-json', 'php-opcache', 'php-mbstring', 'php-xml', 'php-gd', 'php-curl']
centos_mysql_dep : [ 'mysql-community-server', 'MySQL-python', 'python36-mysql' ]
debian_php_fpm: "unix:/var/run/php/php7.0-fpm.sock"
centos_php_fpm: "unix:/var/run/php-fpm/www.sock"
ubuntu_php_fpm: "unix:/var/run/php/php7.2-fpm.sock"
 


mysql_user: "mysql"
mysql_pass: "123"
mysql_database: "wordpress"
mysql_root_user: "root"
mysql_root_password: "root"
body_size: 100M