- name: Ubuntu/Debian System
  become: yes
  block:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Creating Web Data
      file:
        path: /var/www/{{ inventory_hostname }}
        state: directory
        group: '82'
        owner: 'www-data'
        mode: '700'