- name: Nginx Role
  become: yes
  block:
    - name: Installing Nginx
      apt:
        name: nginx
        state: present

    - name: Main Nginx Config
      template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "644"

    - name: Remove The Defaut Website
      file:
        path: /etc/nginx/{{ item }}
        state: absent
      loop: 
        - "sites-enabled/default"
        - "sites-available/default"

    - name: "{{ inventory_hostname }}.{{ chosen_domain }} Web Location"
      file:
        path: /var/www/{{ inventory_hostname }}.{{ chosen_domain }}
        state: directory
        owner: www-data 
        group: www-data 
        mode: "755"

    - name: "Copying {{ inventory_hostname }}.{{ chosen_domain }} config"
      template: 
        src: website.j2
        dest: /etc/nginx/conf.d/{{ inventory_hostname }}.conf
        owner: root
        group: root
        mode: "644"

    - name: "Creating {{ inventory_hostname }}.{{ chosen_domain }} Log"
      file: 
        path : /var/log/nginx/{{ inventory_hostname }}.{{ chosen_domain }}
        state: directory
        owner: root
        group: root
        mode: "640"
      notify: Restart Nginx Service

