---
# tasks file for roles/reverse-proxy
# Comment the task if the file/directory/services is already created or done

- name: Installing epel release
  yum:
    name: epel-release
  tags: epel

- name: Installing Reverse Proxy Nginx and ultilities
  yum:
    name: 
      - nginx
      - httpd-tools
    state: latest
  tags: nginx

- name: Starting Nginx service
  service:
    name: nginx
    state: started
  tags: start service

- name: Creating configuration location
  file:
    path: /etc/nginx/conf.d/{{ server.info[0].fulldomainname }}
    state: directory
    mode: '644'
    owner: root
    group: root
  tags: website config directory 

- name: Creating certificate location
  file:
    path: /etc/nginx/authentication
    state: directory
    mode: '644'
    owner: root
    group: root
  tags: authentication directory

- name: Generate Basic Authen
  shell: "htpasswd -c -b /etc/nginx/authentication/.htpasswd.{{ item.servername }}.{{ item.fulldomainname }} {{ item.servername }} {{ item.basicauthen }}"
  loop: "{{ server.info }}"
  tags: shell
 
- name: Copying configuration
  template:
    src: '../templates/reverse.j2'
    dest: '/etc/nginx/conf.d/{{ item.fulldomainname }}/{{ item.domainname }}.{{ item.fulldomainname }}.conf'
  loop: "{{ server.info }}"
  tags: copy
  

- name: Edit Configuration
  lineinfile:
    path: /etc/nginx/nginx.conf
    backrefs: yes
    regexp: '^(\s*)[#]?include /etc/nginx/conf.d/;*'
    line: '\1include /etc/nginx/conf.d/{{ server.info[0].fulldomainname }}/*.conf;'
    state: "present"
  changed_when: true
  notify: 
   - Restarting Reverse-Proxy
  tags: editing config
