- name: HAProxy Setup
  become: yes 
  block:
    - name: Installing HAProxy
      apt: 
        name: "{{ item }}"
        state: present
      loop:
        - haproxy
        - python-mysqldb

    - name: HAProxy Config
      template:
        src: haproxy.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: "644"
        validate: 'haproxy -c -f %s'
      notify: Restart HAProxy



