debian_mysql_deps: [ 'mysql-server' , 'python-mysqldb', ' python3-mysqldb' ]
centos_mysql_dep : [ 'mysql-community-server', 'MySQL-python', 'python36-mysql' ]


mysql_user: "mysql"
mysql_pass: "123"
mysql_database: "wordpress"
mysql_root_user: "root"
mysql_root_password: "root"