---
# handlers file for roles/webserver

- name: Restart Nginx Config
  shell: nginx -s reload

- name: Restart Nginx Service
  service: 
    name: nginx
    state: restarted


- name: Restart CentOS PHP-FPM Service
  service:
    name: php-fpm
    state: restarted
  when: ansible_distribution == "CentOS"
  listen: "Restart PHP-FPM Service"
- name: Restart Ubuntu PHP-FPM Service
  service:
    name: php7.2-fpm
    state: restarted
  when: ansible_distribution == "Ubuntu"
  listen: "Restart PHP-FPM Service"
- name: Restart Debian PHP-FPM Service
  service:
    name: php7.0-fpm
    tate: restarted
  when: ansible_distribution == "Debian"
  listen: "Restart PHP-FPM Service"
  

