- name: Wordpress Setup
  become: yes
  block:
    - name: Download and Unpack Wordpress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/{{ inventory_hostname }}
        validate_certs: no
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Conpying Wordpress Config FIle
      template:
        src: wp-config.j2
        dest: /var/www/html/{{ domain }}/wp-config.php
        owner: www-data
        group: www-data
        mode: "755"