- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Wordpress Role 
  become: yes
  block:
    - name: Get API Information For wp-config
      no_log: True
      uri:
        url: "https://api.wordpress.org/secret-key/1.1/salt/"
        return_content: True
        method: GET
      register: key_info
      
    - name: Insert Unique Keys and Salts In wp-config
      lineinfile:
        path: /var/www/{{ inventory_hostname }}/wp-config.php
        regex: "put your unique phrase here"
        insertafter: "put your unique phrase here"
        line: "{{ key_info.content }}"

    - name: Remove Default Keys and Salts In wp-config
      lineinfile:
        path: /var/www/{{ inventory_hostname }}/wp-config.php
        regex: "put your unique phrase here"
        state: "absent"


