- name: CentOS Dependencies
  yum:
    name: "{{ item }}"
    state: "present" 
  loop: "{{ centos_deps }}"
  when: ansible_distribution == "CentOS" 

- name: Ubuntu and Debian Dependencies
  apt: 
    name: "{{ item }}"
    state: "present"
  loop: "{{ debian_deps }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
