---
# tasks file for roles/webserver




- include: installing-deps.yaml
- include: php.yaml
- include: create-folder.yaml
- include: mysql.yaml
- include: ssl.yaml
- include: wordpress.yaml
- include: nginx.yaml
- include: services.yaml





