---
# tasks file for roles/webserver




- include: installing-deps.yaml
- include: nginx.yaml
- include: ssl.yaml
- include: php.yaml
- include: mysql.yaml
- include: wordpress.yaml
- include: services.yaml



# - name: MYSQL password
#   debug: 
#     msg: "{{ loginfact }}"





