- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: SSL/TLS Setup
  become: yes
  block:  
    - name: Generate Website Private key
      openssl_privatekey:
        path: /etc/ssl/certs/haproxy.key
        size: 2048
        type: RSA

    - name: Generate Certificate Signing Request
      openssl_csr:
        path: /etc/ssl/certs/haproxy.csr
        privatekey_path: /etc/ssl/certs/haproxy.key

    - name: Generate a Self Signed OpenSSL certificate
      openssl_certificate:
        path: /etc/ssl/certs/haproxy.crt
        privatekey_path: /etc/ssl/certs/haproxy.key
        csr_path: /etc/ssl/certs/haproxy.csr
        provider: selfsigned
      register: haproxy_certificate
    
    - name: Create pem file
      shell: cat /etc/ssl/certs/haproxy.key /etc/ssl/certs/haproxy.crt > /etc/ssl/certs/haproxy.pem
      when: haproxy_certificate is changed