- name: PHP Role
  become: yes 
  block:
    - name: CentOS/RedHat System
      block:
        - name: Installing PHP repo
          yum:
            name: "{{ php_repo }}"
            state: present
        
        - name: Installing PHP Modules
          yum:
            name: "{{ item }}"
            state: present
            enablerepo: remi-php74
        
        - name: CentOS PHP-FPM Pre-Config
          lineinfile:
            path: /etc/php-fpm.d/www.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            state: present
          with_items:
          - { regexp: "user = apache", line: "user = nginx"}
          - { regexp: "group = apache", line: "group = nginx"}
          - { regexp: "listen = 127.0.0.1:9000", line: "listen = /run/php-fpm/www.sock"}
          - { regexp: ";listen.owner = nobody", line: "listen.owner = nginx"}
          - { regexp: ";listen.group = nobody", line: "listen.group = nginx"}

        - name: Change /var/lib/php Ownership
          file:
            path: /var/lib/php
            owner: root
            group: nginx
            state: directory
            recurse: yes

        - name: Change PHP-FPM Upload Size
          lineinfile:
            path: /etc/php.ini
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            state: present
          with_items:
            - { regexp : "post_max_size =", line : "post_max_size = {{ body_size }}" }
            - { regexp : "upload_max_filesize =", line : "upload_max_filesize = {{ body_size }}" }
          notify: Starting CentOS PHP-FPM Service
        
      when: ansible_distribution == "CentOS"

    - name: Debian/Ubuntu System
      block:
        - name: Ubuntu System
          block:
            - name: Installing PHP repo
              apt_repository:
                repo: ppa:ondrej/php

            - name: Installing PHP Modules
              apt:
                name: "{{ dep_php }}"
                state: present
            
          when: ansible_distribution == "Ubuntu"

        - name: Change PHP-FPM Upload Size
          lineinfile:
            path: /etc/php/7.4/fpm/php.ini
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
          with_items:
            - { regexp : "post_max_size =", line : "post_max_size = {{ body_size }}" }
            - { regexp : "upload_max_filesize =", line : "upload_max_filesize = {{ body_size }}" }
        
        - name: Starting PHP-FPM Service
          service:
            name: php7.4-fpm
            state: restarted
            
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"


- name: Installing Debian and Ubuntu PHP modules
  apt: 
    name: "{{ item }}"
    state: "present"
  loop: "{{ deb_php }}"
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: PHP-FPM
  block:
    - name: Starting Ubuntu PHP-FPM Service
      service:
        name: php7.2-fpm
        state: started
      when: ansible_distribution == "Ubuntu"
    - name: Change PHP-FPM Upload Size
      lineinfile:
        path: /etc/php/7.2/fpm/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: "present"
      with_items:
        - { "regexp" : "post_max_size =", "line" : "post_max_size = {{ body_size }}" }
        - { "regexp" : "upload_max_filesize =", "line" : "upload_max_filesize = {{ body_size }}" }
      notify: Restart PHP-FPM Service
      when: ansible_distribution == "Ubuntu"
    - name: Starting Debian PHP-FPM Service
      service:
        name: php7.0-fpm
        tate: started
      when: ansible_distribution == "Debian"
  
